<?php
/*
  Implements hook_theme_suggestions_html_alter
*/
function futusign_theme_suggestions_html_alter(array &$suggestions, array $variables) {
  if ($node = Drupal::request()->attributes->get('node')) {
    $is_admin = Drupal::service('router.admin_context')->isAdminRoute();
    $content_type = $node->bundle();
    if ($content_type == 'futusign_screen' && $is_admin == 0) {
      $suggestions[] = 'html__futusign_screen';
    }
  }
}
/*
  Implements hook_preprocess_html
*/
function futusign_preprocess_html(&$variables) {
  global $base_root, $base_path;
  if ($node = Drupal::request()->attributes->get('node')) {
    $content_type = $node->bundle();
    if ($content_type == 'futusign_screen') {
      $variables['base_root'] = $base_root;
      $variables['app_root'] = $base_root . $base_path . drupal_get_path('module', 'futusign') . '/templates/screen/dist';
      $variables['node_id'] = $node->id();
    }
  }
}
/*
  Implements hook_theme
*/
function futusign_theme($existing, $type, $theme, $path) {
  return array(
    'html__futusign_screen' => array(
      'path' => drupal_get_path('module', 'futusign') . '/templates/screen/dist',
      'template' => 'index',
      'override preprocess functions' => true,
      'preprocess functions' => array(
        'futusign_preprocess_html',
      ),
    ),
  );
}
